# Generated by Django 5.1.7 on 2025-03-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('attendance', '0003_remove_attendance_attendance_percentage'),
    ]

    operations = [
    ]
